# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'


steps:
- task: PowerShell@2
  inputs:
    targetType: filePath
    filePath: './.test/Test-DynamicTask-1-PR.ps1'
    arguments: '-ExcutePSFile "Test-DynamicTask-Main-Continuous.ps1"'
  env:

    #PAT: '4wkuiqj64xlyym6y52wnefq3lypbmrj2kuimc5ksv24cnbsng3kq'  
    PAT: 'lo57v5gjdy3k5rt3iusvvjjlhflz2cxz2yey4xkps6efslsdnvea'

    OrganizationName: 'ChloeQian123'

    ProjectName: 'ChloeQian123.github.io'
    
    ReposName: 'master'

    WikiName: '%%WikiName%%'

    GeneralPages: 'GeneralPages,SharedPages'

    GlobalUserEmail: 'v-jichlo@microsoft.com
    GlobalUserName: 'Chloe Chloe'
    ExcutePSFile: 'Test-DynamicTask-Main-Continuous.ps1'

    Server: 'csswiki.database.windows.net'

    Database: 'CSSWikiDynamicDB'

    UserName: 'DaleChe'

    Password: 'content@CssFY20,'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

