# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#echo Installing $(deploy_key.secureFilePath) to the trusted CA directory...
#sudo chown root:root $(deploy_key.secureFilePath)
#sudo chmod a+r $(deploy_key.secureFilePath)
#sudo ln -s -t /etc/ssl/certs/ $(deploy_key.secureFilePath)
#Copy-Item -Path $(Agent.WorkFolder)\_temp\filename -Destination $(Build.ArtifactStagingDirectory)
    


trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'


steps:
- task: PowerShell@2
  inputs:
    targetType: filePath
    filePath: './.test/Test-DynamicTask-1-PR.ps1'
    arguments: '-ExcutePSFile "Test-DynamicTask-Main-Continuous.ps1"'
  env:

    #PAT: '4wkuiqj64xlyym6y52wnefq3lypbmrj2kuimc5ksv24cnbsng3kq'  
    PAT: 'a3uo3y45afx56ut5ppcalw7pji7bt4jw2bvw5ffxupw2vnsytgqq'

    OrganizationName: 'ChloeQian123'

    ProjectName: 'ChloeQian123.github.io'
    
    ReposName: 'ChloeQian123.github.io'

    WikiName: '%%WikiName%%'

    GeneralPages: 'GeneralPages,SharedPages'

    GlobalUserEmail: 'v-jichlo@microsoft.com'
    GlobalUserName: 'Chloe Chloe'
    ExcutePSFile: 'Test-DynamicTask-Main-Continuous.ps1'

    Server: 'csswiki.database.windows.net'

    Database: 'CSSWikiDynamicDB'

    UserName: 'DaleChe'

    Password: 'content@CssFY20,'


- task: DownloadSecureFile@1
  name: deploy_key
  displayName: 'Download deploy_key'
  inputs:
    secureFile: 'deploy_key'

- script: |
    Copy-Item  -Path $(deploy_key.secureFilePath) -Destination c:\.ssh\deploy_key


- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

