# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PowerShell@2
  inputs:
    targetType: filePath
    filePath: './.test/Test-DynamicTask-ToGitHub.ps1'
    #arguments: '-ExcutePSFile "Test-DynamicTask-Main-Continuous.ps1"'
  env:

    #PAT: '4wkuiqj64xlyym6y52wnefq3lypbmrj2kuimc5ksv24cnbsng3kq'  
    PAT: 'a3uo3y45afx56ut5ppcalw7pji7bt4jw2bvw5ffxupw2vnsytgqq'

    OrganizationName: 'ChloeQian123'

    ProjectName: 'ChloeQian123.github.io'
    
    ReposName: 'ChloeQian123.github.io'

    WikiName: '%%WikiName%%'

    GeneralPages: 'GeneralPages,SharedPages'

    GlobalUserEmail: 'v-jichlo@microsoft.com'
    GlobalUserName: 'Chloe Chloe'
    ExcutePSFile: 'Test-DynamicTask-Main-Continuous.ps1'

    Server: 'csswiki.database.windows.net'

    Database: 'CSSWikiDynamicDB'

    UserName: 'DaleChe'

    Password: 'content@CssFY20,'
